server:
    port: 8888
spring:
    thymeleaf:
        cache: false
        enabled: false
    application:
        name: bees
    datasource:
        url: jdbc:mysql://47.98.54.210/demo2?autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
        username: root
        password: a123456
        driver-class-name: com.mysql.jdbc.Driver
        initial-size: 20
        max-active: 100
        max-idle: 5
        max-wait: 10000
        min-idle: 1
        testOnBorrow: true
        validationQuery: SELECT 1
    redis:
        database: 0
        host: 192.168.1.5
        port: 7000
        password: ''
        timeout: 10000
        jedis:
            pool:
                max-active: 100
                max-wait: 10000
                max-idle: 20
                min-idle: 8

## 日志支持
logging:
    file: ./log/demo.log
    level:
        com:
            angrywolves: WARN
        java:
            sql: INFO
mybatis: 
    mapperLocations: classpath:mybatis/*.xml
    typeAliasesPackage: com.xulu.demo